# Generated by Django 2.2.6 on 2019-11-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
