# Generated by Django 2.2.6 on 2019-11-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191110_2004'),
        ('quiz', '0007_auto_20191110_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
    ]
