# Generated by Django 2.2.6 on 2019-11-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20191112_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_back',
            new_name='feedback',
        ),
    ]
